CarpoolApp/CarpoolApp/Areas/Driver/ViewModels/Obavijesti/ObavijestDodajVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarpoolApp.Areas.Driver.ViewModels.Obavijesti
{
    public class ObavijestDodajVM
    {
        public string Naslov { get; set; }
        public int TipObavijesti { get; set; }
        public List<SelectListItem> tipovi { get; set; }
        public string KratkiOpis { get; set; }
        public DateTime DatumVrijemeObjave { get; set; }
    }
}

CarpoolApp/CarpoolApp/Areas/Driver/ViewModels/Obavijesti/ObavijestiDetaljiVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarpoolApp.Models;
using ReflectionIT.Mvc.Paging;

namespace CarpoolApp.Areas.Driver.ViewModels.Obavijesti
{
    public class ObavijestiDetaljiVM
    {
        public PagingList<Row> Obavijesti { get; set; }
        public int Page { get; set; } = 1;

        public class Row
        {
            public int ObavijestiID { get; set; }
            public string KratkiOpis { get; set; }
            public string Naslov { get; set; }
            public DateTime DatumVrijemeObjave { get; set; }

            public int TipObavijestiID { get; set; }
            public TipObavijesti TipObavijesti { get; set; }
            public string KorisnickoIme { get; set; }
        }
    }
}

CarpoolApp/CarpoolApp/Areas/Driver/ViewModels/Obavijesti/ObavijestiUrediVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarpoolApp.Areas.Driver.ViewModels.Obavijesti
{
    public class ObavijestiUrediVM: ObavijestDodajVM
    {
        public int ObavijestId { get; set; }
    }
}

CarpoolApp/CarpoolApp/Models/Obavijesti.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarpoolApp.Models
{
    public class Obavijesti
    {
        public int ObavijestiID { get; set; }
        public string KratkiOpis { get; set; }
        public string Naslov { get; set; }
        public DateTime DatumVrijemeObjave { get; set; }

        public int TipObavijestiID { get; set; }
        public TipObavijesti TipObavijesti { get; set; }

        public bool Vaznost { get; set; }

        public int VozacID { get; set; }
        public Vozac Vozac { get; set; }
    }
}

CarpoolApp/CarpoolApp/Areas/Driver/Controllers/ObavijestiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarpoolApp.Areas.Driver.ViewModels.Obavijesti;
using CarpoolApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;

namespace CarpoolApp.Areas.Driver.Controllers
{
    public class ObavijestiController : BaseController
    {
        public ObavijestiController(CarpoolAppContext db) : base(db)
        {
        }
        public IActionResult Detalji()
        {
            return View();
        }

        public async Task<IActionResult> SveObavijesti(ObavijestiDetaljiVM model)
        {
            ObavijestiDetaljiVM lista = new ObavijestiDetaljiVM();


            var obavijesti = _db.Obavijesti
                .OrderByDescending(x => x.DatumVrijemeObjave)
                 .Select(x => new ObavijestiDetaljiVM.Row()
                 {
                     Naslov = x.Naslov,
                     KratkiOpis = x.KratkiOpis,
                     DatumVrijemeObjave = x.DatumVrijemeObjave,
                     ObavijestiID = x.ObavijestiID,
                     TipObavijestiID = x.TipObavijestiID,
                     TipObavijesti = x.TipObavijesti,
                     KorisnickoIme = x.Vozac.Korisnik.Ime + " " + x.Vozac.Korisnik.Prezime
                 });

            lista.Obavijesti = await PagingList.CreateAsync((IOrderedQueryable<ObavijestiDetaljiVM.Row>)obavijesti, 3, model.Page);
            return PartialView(lista);
        }

        public async Task<IActionResult> LicneObavijesti(ObavijestiDetaljiVM model)
        {
            ObavijestiDetaljiVM lista = new ObavijestiDetaljiVM();

            int vozac = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            var obavijesti = _db.Obavijesti.Where(o => o.VozacID == vozac)
                 .OrderByDescending(x => x.DatumVrijemeObjave)
                 .Select(x => new ObavijestiDetaljiVM.Row()
                 {
                     Naslov = x.Naslov,
                     KratkiOpis = x.KratkiOpis,
                     DatumVrijemeObjave = x.DatumVrijemeObjave,
                     ObavijestiID = x.ObavijestiID,
                     TipObavijestiID = x.TipObavijestiID,
                     TipObavijesti = x.TipObavijesti,
                     KorisnickoIme = x.Vozac.Korisnik.Ime + " " + x.Vozac.Korisnik.Prezime
                 });

            lista.Obavijesti = await PagingList.CreateAsync((IOrderedQueryable<ObavijestiDetaljiVM.Row>)obavijesti, 3, model.Page);
            return PartialView(lista);
        }

        public IActionResult Obrisi(int obavijestiId)
        {
            Obavijesti obavijest = _db.Obavijesti.Find(obavijestiId);
            _db.Obavijesti.Remove(obavijest);

            _db.SaveChanges();

            return RedirectToAction(nameof(Detalji));
        }
        public IActionResult Dodaj()
        {
            ObavijestDodajVM Model = new ObavijestDodajVM();
            Model.tipovi = new List<SelectListItem>();
            Model.tipovi = _db.TipObavijesti.Select(t => new SelectListItem()
            {
                Value = t.TipObavijestiID.ToString(),
                Text = t.NazivTipa
            }).ToList();

            return View(Model);
        }

        [HttpPost]
        public IActionResult Dodaj(ObavijestDodajVM Model)
        {
            _db.Obavijesti.Add(new Obavijesti
            {
                VozacID = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)),
                Naslov = Model.Naslov,
                DatumVrijemeObjave = DateTime.Now,
                KratkiOpis = Model.KratkiOpis,
                TipObavijestiID = Model.TipObavijesti
            });

            _db.SaveChanges();

            return RedirectToActionPermanent(nameof(Detalji));
        }

        public IActionResult Uredi(int obavijestiId)
        {
            Obavijesti o = _db.Obavijesti.Find(obavijestiId);
            var model = new ObavijestiUrediVM
            {
                DatumVrijemeObjave = o.DatumVrijemeObjave,
                KratkiOpis = o.KratkiOpis,
                TipObavijesti = o.TipObavijestiID,
                ObavijestId = obavijestiId,
                Naslov = o.Naslov,

                tipovi = _db.TipObavijesti.Select(t => new SelectListItem()
                {
                    Value = t.TipObavijestiID.ToString(),
                    Text = t.NazivTipa
                }).ToList()
            };

            return View("Uredi", model);
        }

        [HttpPost]
        public IActionResult Uredi(ObavijestiUrediVM mod)
        {

            Obavijesti obavijesti = _db.Obavijesti.Find(mod.ObavijestId);

            obavijesti.Naslov = mod.Naslov;
            obavijesti.KratkiOpis = mod.KratkiOpis;
            obavijesti.TipObavijestiID = mod.TipObavijesti;

            _db.Obavijesti.Update(obavijesti);
            _db.SaveChanges();

            return RedirectToAction(nameof(Detalji));
        }
    }
}

CarpoolApp/CarpoolApp/Areas/Driver/Views/Obavijesti/Detalji.cshtml
@model CarpoolApp.Areas.Driver.ViewModels.Obavijesti.ObavijestiDetaljiVM

@{
    ViewData["Title"] = "Detalji";
}

<link href="~/bootstrapTheme/css/freelancer.css" rel="stylesheet" asp-append-version="true">

<!-- About Section -->
<section class="page-section bg-primary text-white mb-0 portfolio" id="about">
    <div class="container">

        <!-- About Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-white">Obavijesti</h2>

        <!-- Icon Divider -->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-newspaper"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Button -->
        <div class="text-center mt-4">
            <a class="btn btn-xl btn-outline-light btnObavijest" asp-area="Driver" asp-controller="Obavijesti" asp-action="Dodaj">
                <i class="fas fa-plus mr-2"></i>
                Dodaj obavijest
            </a>
            <a class="btn btn-xl btn-outline-light btnObavijest" ajax-poziv="da" ajax-rezultat="obavijestiDiv" href="/Driver/Obavijesti/LicneObavijesti" @*asp-area="Driver" asp-controller="Obavijesti" asp-action="LicneObavijesti"*@>
                <i class="fas fa-user mr-2"></i>
                Moje obavijesti
            </a>
            <a class="btn btn-xl btn-outline-light btnObavijest"
               ajax-poziv="da" ajax-rezultat="obavijestiDiv" href="/Driver/Obavijesti/SveObavijesti">
                <i class="fas fa-scroll mr-2"></i>
                Sve obavijesti
            </a>
        </div>

        <div class="row" id="obavijestiDiv">

        </div>

    </div>
</section>

CarpoolApp/CarpoolApp/Areas/Driver/Views/Obavijesti/Dodaj.cshtml
@model CarpoolApp.Areas.Driver.ViewModels.Obavijesti.ObavijestDodajVM
@{
    ViewData["Title"] = "Dodaj";
}

<!-- Custom scripts for this template -->
<script src="~/bootstrapTheme/js/freelancer.min.js" asp-append-version="true"></script>

<!-- Contact Section -->
<section class="page-section portfolio" id="contact">
    <div class="container">

        <!-- Contact Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Dodaj obavijest</h2>

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-newspaper"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Contact Section Form -->
        <div class="row">
            <div class="col-lg-8 mx-auto">

                <form enctype="multipart/form-data" action="Dodaj" method="post">
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Naslov</label>
                            <input asp-for="Naslov" class="form-control" id="name" type="text" required="required" placeholder="Naslov" data-validation-required-message="Molimo Vas unesite naslov sadržaja.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">                
                            <label>Tip obavijesti</label>
                            <select asp-for="TipObavijesti" asp-items="Model.tipovi" class="form-control">
                                <option disabled="disabled">(odaberite tip)</option>
                            </select>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Kratki opis</label>
                            <textarea asp-for="KratkiOpis" class="form-control" id="message" rows="5" placeholder=". . ." required="required" data-validation-required-message="Molimo Vas unesite sadržaj."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>

                    <br>
                    <div id="success"></div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-xl">Objavi</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</section>

CarpoolApp/CarpoolApp/Areas/Driver/Views/Obavijesti/LicneObavijesti.cshtml
@model CarpoolApp.Areas.Driver.ViewModels.Obavijesti.ObavijestiDetaljiVM
@using CarpoolApp.Helper
@{
    ViewData["Title"] = "Index";
}
<script src="~/jsFIT.js" asp-append-version="true"></script>
<link href="~/css/Obavijesti.css" rel="stylesheet" asp-append-version="true">

<div class="row">
    @for (var i = 0; i < Model.Obavijesti.Count(); i++)
    {
        <!-- Main Content -->
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-preview">
                        <a asp-controller="Obavijesti" asp-area="Driver" asp-action="Uredi" asp-route-obavijestiId="@Model.Obavijesti[i].ObavijestiID">
                            <h2 class="post-title">
                                @Model.Obavijesti[i].Naslov
                            </h2>
                            @if (Model.Obavijesti[i].TipObavijesti.NazivTipa == "Hitno")
                            {
                                <h3 class="post-subtitle">
                                    @Model.Obavijesti[i].KratkiOpis.Substring(0, @Model.Obavijesti[i].KratkiOpis.IndexOf(".") + 1)
                                </h3>
                                <i style="color:red;" class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                            }
                            else
                            {
                                <h3 class="post-subtitle">
                                    @Model.Obavijesti[i].KratkiOpis.Substring(0, @Model.Obavijesti[i].KratkiOpis.IndexOf(".") + 1)
                                </h3>
                                <i style="color:lightblue;" class="fa fa-info-circle" aria-hidden="true"></i>
                            }
                        </a>
                        @*<a href="#"><i class="fas fa-edit fa-lg"></i></a>*@
                        <p class="post-meta">
                            Objavio/la @Model.Obavijesti[i].KorisnickoIme @DateTimeHelper.GetFriendlyRelativeTime(Model.Obavijesti[i].DatumVrijemeObjave)
                        </p>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    }
    <div class="formPagination">
        <form ajax-url="/Driver/Obavijesti/LicneObavijesti" ajax-result="obavijestiDiv" class="pagination justify-content-center">
            <vc:pagination paging-list="@Model.Obavijesti" />
        </form>
    </div>
</div>

CarpoolApp/CarpoolApp/Areas/Driver/Views/Obavijesti/SveObavijesti.cshtml
@model CarpoolApp.Areas.Driver.ViewModels.Obavijesti.ObavijestiDetaljiVM
@using CarpoolApp.Helper

@*@model ReflectionIT.Mvc.Paging.PagingList<CarpoolApp.Models.Obavijesti>
    @using ReflectionIT.Mvc.Paging
    @addTagHelper *, ReflectionIT.Mvc.Paging*@

@{
    ViewData["Title"] = "SveObavijesti";
}

<script src="~/jsFIT.js" asp-append-version="true"></script>
<!-- Custom styles for this template -->
<link href="~/css/Obavijesti.css" rel="stylesheet" asp-append-version="true">

<div class="row">
    @for (var i = 0; i < Model.Obavijesti.Count(); i++)
    {
        <!-- Main Content -->
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-preview">
                        <a href="post.html">
                            <h2 class="post-title">
                                @Model.Obavijesti[i].Naslov
                            </h2>
                            @if (Model.Obavijesti[i].TipObavijesti.NazivTipa == "Hitno")
                            {
                                <h3 class="post-subtitle">
                                    @Model.Obavijesti[i].KratkiOpis.Substring(0, @Model.Obavijesti[i].KratkiOpis.IndexOf(".") + 1)
                                </h3>
                                <i style="color:red;" class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                            }
                            else
                            {
                                <h3 class="post-subtitle">
                                    @Model.Obavijesti[i].KratkiOpis.Substring(0, @Model.Obavijesti[i].KratkiOpis.IndexOf(".") + 1)
                                </h3>
                                <i style="color:lightblue;" class="fa fa-info-circle" aria-hidden="true"></i>
                            }
                        </a>
                        <p class="post-meta">
                            Objavio/la @Model.Obavijesti[i].KorisnickoIme @DateTimeHelper.GetFriendlyRelativeTime(Model.Obavijesti[i].DatumVrijemeObjave)
                        </p>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    }
</div>

    <div class="formPagination">
        <form ajax-url="/Driver/Obavijesti/SveObavijesti" ajax-result="obavijestiDiv" class="pagination justify-content-center">
            <vc:pagination paging-list="@Model.Obavijesti" />
        </form>
    </div>

CarpoolApp/CarpoolApp/Areas/Driver/Views/Obavijesti/Uredi.cshtml
@model CarpoolApp.Areas.Driver.ViewModels.Obavijesti.ObavijestiUrediVM
@{
    ViewData["Title"] = "Uredi";
}

<!-- Custom scripts for this template -->
<script src="~/bootstrapTheme/js/freelancer.min.js" asp-append-version="true"></script>

<!-- Contact Section -->
<section class="page-section portfolio" id="contact">
    <div class="container">

        <!-- Contact Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Uredi obavijest</h2>

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-edit"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Contact Section Form -->
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <input asp-for="ObavijestId" hidden="hidden" />
                <form enctype="multipart/form-data" action="Dodaj" method="post">
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Naslov</label>
                            <input asp-for="Naslov" class="form-control" id="name" type="text" required="required" placeholder="Naslov" data-validation-required-message="Molimo Vas unesite naslov sadržaja.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <label>Tip obavijesti</label>
                        <select asp-for="TipObavijesti" asp-items="Model.tipovi" class="form-control">
                            <option disabled="disabled">(odaberite tip)</option>
                        </select>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            <label>Kratki opis</label>
                            <textarea asp-for="KratkiOpis" class="form-control" id="message" rows="5" placeholder=". . ." required="required" data-validation-required-message="Molimo Vas unesite sadržaj."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>

                    <br>
                    <div id="success"></div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-xl">Spremi</button>
                        <a asp-area="Driver" asp-controller="Obavijesti" asp-action="Obrisi" asp-route-obavijestiId="@Model.ObavijestId" class="btn btn-danger btn-xl">Obriši</a>
                    </div>
                </form>
            </div>
        </div>

    </div>
</section>