CarpoolApp/CarpoolApp/Areas/Driver/ViewModels/Voznje/CijenaVoznjeVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarpoolApp.Areas.Driver.ViewModels.Voznje
{
    public class CijenaVoznjeVM
    {
        public int VoznjaID { get; set; }
        public string GradPolazak { get; set; }
        public string GradDestinacija { get; set; }
        public List<Row> rows { get; set; }

        public CijenaVoznjeVM()
        {
            rows = new List<Row>();
        }
        public class Row
        {
            public int UsputniGradID { get; set; }
            public string UsputniNaziv { get; set; }
            [DataType(DataType.Currency)]
            [DisplayFormat(DataFormatString = "{0:#,##0.00#}", ApplyFormatInEditMode = true)]
            public decimal UsputniCijena { get; set; }
        }
    }
}

CarpoolApp/CarpoolApp/Areas/Driver/ViewModels/Voznje/SveVoznjeVM.cs
using CarpoolApp.Models;
using ReflectionIT.Mvc.Paging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarpoolApp.Areas.Driver.ViewModels.Voznje
{
    public class SveVoznjeVM
    {
        public int CurrentUser { get; set; }
        public List<Row> voznje { get; set; }

        public SveVoznjeVM()
        {
            voznje = new List<Row>();
        }

        public class Usputni
        {
            public int UsputniGradId { get; set; }
            public string Naziv { get; set; }
            public decimal Cijena { get; set; }
        }
        public class Row
        {
            public int VoznjaID { get; set; }
            public int KorisnikID { get; set; }
            public string KorisnickoIme { get; set; }
            public DateTime DatumPolaska { get; set; }
            public DateTime VrijemePolaska { get; set; }
            public int SlobodnaMjesta { get; set; }
            public decimal PunaCijena { get; set; }
            public string GradPolaska { get; set; }
            public string GradDestinacija { get; set; }
            public string SlikaPath { get; set; }
            public string AutoNazivModel { get; set; }

            public List<Usputni> usputni { get; set; }
        }
    }
}

CarpoolApp/CarpoolApp/Areas/Driver/ViewModels/Voznje/VoznjeDodajVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarpoolApp.Areas.Driver.ViewModels.Voznje
{
    public class VoznjeDodajVM
    {
        public int VoznjaID { get; set; }
        public int VozacID { get; set; }
        public int GradPolaskaID { get; set; }
        public List<SelectListItem> GradPolaska { get; set; }

        public int GradDestinacijaID { get; set; }
        public List<SelectListItem> GradDestinacija { get; set; }

        [DataType(DataType.Date)]
        public DateTime DatumPolaska { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:H:mm}")]
        public DateTime VrijemePolaska { get; set; }
        public int SlobodnaMjesta { get; set; }

        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:#,##0.00#}", ApplyFormatInEditMode = true)]
        public decimal PunaCijena { get; set; }
        public int AutomobilID { get; set; }
        public List<SelectListItem> Automobili { get; set; }

        public List<int> SelektiraniGradovi { get; set; }
        public IEnumerable<SelectListItem> UsputniGradovi { get; set; }

    }
}

CarpoolApp/CarpoolApp/Areas/Driver/ViewModels/Voznje/VoznjeUrediVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarpoolApp.Areas.Driver.ViewModels.Voznje
{
    public class VoznjeUrediVM: VoznjeDodajVM
    {

    }
}

CarpoolApp/CarpoolApp/Areas/Driver/Controllers/VoznjeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarpoolApp.Areas.Driver.ViewModels.Voznje;
using CarpoolApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;

namespace CarpoolApp.Areas.Driver.Controllers
{
    public class VoznjeController : BaseController
    {
        public VoznjeController(CarpoolAppContext db) : base(db)
        {
        }

        public IActionResult Detalji()
        {
            return View();
        }
        public IActionResult SveVoznje()
        {
            SveVoznjeVM model = new SveVoznjeVM();

            model.CurrentUser = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            model.voznje = _db.Voznje
                .Where(a => a.SlobodnaMjesta > 0 && a.IsAktivna)
                .OrderByDescending(v => v.DatumObjave).Select(v => new SveVoznjeVM.Row
                {
                    AutoNazivModel = v.Automobil.Naziv + " " + v.Automobil.Model,
                    SlikaPath = v.Automobil.SlikaPath,
                    DatumPolaska = v.DatumPolaska,
                    VrijemePolaska = v.VrijemePolaska,
                    PunaCijena = v.PunaCijena,
                    SlobodnaMjesta = v.SlobodnaMjesta,
                    GradPolaska = v.GradPolaska.Naziv,
                    GradDestinacija = v.GradDestinacija.Naziv,
                    KorisnikID = v.VozacID,

                    usputni = _db.UsputniGradovi.Where(u => u.VoznjaID == v.VoznjaID).Select(u => new SveVoznjeVM.Usputni
                    {
                        UsputniGradId = u.UsputniGradoviID,
                        Cijena = u.CijenaUsputni,
                        Naziv = u.Grad.Naziv
                    }).ToList(),

                    VoznjaID = v.VoznjaID,
                    KorisnickoIme = v.Vozac.Korisnik.Ime + " " + v.Vozac.Korisnik.Prezime
                }).ToList();

            return View(model);
        }

        public IActionResult SearchVoznje(int odredisteId, int polazisteId)
        {
            SveVoznjeVM model = new SveVoznjeVM();

            model.voznje = _db.Voznje
                .Where(v => (v.GradPolaskaID == polazisteId && v.GradDestinacijaID == odredisteId) || (v.UsputniGradovi.Any(a => a.GradID == odredisteId) && v.GradPolaskaID == polazisteId))
                .OrderByDescending(v => v.DatumObjave).Select(v => new SveVoznjeVM.Row
                {
                    AutoNazivModel = v.Automobil.Naziv + " " + v.Automobil.Model,
                    SlikaPath = v.Automobil.SlikaPath,
                    DatumPolaska = v.DatumPolaska,
                    VrijemePolaska = v.VrijemePolaska,
                    PunaCijena = v.PunaCijena,
                    SlobodnaMjesta = v.SlobodnaMjesta,
                    GradPolaska = v.GradPolaska.Naziv,
                    GradDestinacija = v.GradDestinacija.Naziv,
                    usputni = _db.UsputniGradovi.Where(u => u.VoznjaID == v.VoznjaID).Select(u => new SveVoznjeVM.Usputni
                    {
                        UsputniGradId = u.UsputniGradoviID,
                        Cijena = u.CijenaUsputni,
                        Naziv = u.Grad.Naziv
                    }).ToList(),
                    VoznjaID = v.VoznjaID,
                    KorisnickoIme = v.Vozac.Korisnik.Ime + " " + v.Vozac.Korisnik.Prezime
                }).ToList();

            return View(model);
        }


        public IActionResult MojeVoznje(int vozacID)
        {
            SveVoznjeVM model = new SveVoznjeVM();

            model.CurrentUser = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            model.voznje = _db.Voznje
                .Where(a => a.VozacID == vozacID && a.IsAktivna)
                .OrderByDescending(v => v.DatumObjave).Select(v => new SveVoznjeVM.Row
                {
                    AutoNazivModel = v.Automobil.Naziv + " " + v.Automobil.Model,
                    SlikaPath = v.Automobil.SlikaPath,
                    DatumPolaska = v.DatumPolaska,
                    VrijemePolaska = v.VrijemePolaska,
                    PunaCijena = v.PunaCijena,
                    SlobodnaMjesta = v.SlobodnaMjesta,
                    GradPolaska = v.GradPolaska.Naziv,
                    GradDestinacija = v.GradDestinacija.Naziv,
                    KorisnikID = v.VozacID,

                    usputni = _db.UsputniGradovi.Where(u => u.VoznjaID == v.VoznjaID).Select(u => new SveVoznjeVM.Usputni
                    {
                        UsputniGradId = u.UsputniGradoviID,
                        Cijena = u.CijenaUsputni,
                        Naziv = u.Grad.Naziv
                    }).ToList(),

                    VoznjaID = v.VoznjaID,
                    KorisnickoIme = v.Vozac.Korisnik.Ime + " " + v.Vozac.Korisnik.Prezime
                }).ToList();

            return View(model);
        }

        public IActionResult ZavrseneVoznje(int vozacID)
        {
            SveVoznjeVM model = new SveVoznjeVM();

            model.CurrentUser = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            model.voznje = _db.Voznje
                .Where(a => a.VozacID == vozacID && !a.IsAktivna)
                .OrderByDescending(v => v.DatumObjave).Select(v => new SveVoznjeVM.Row
                {
                    AutoNazivModel = v.Automobil.Naziv + " " + v.Automobil.Model,
                    SlikaPath = v.Automobil.SlikaPath,
                    DatumPolaska = v.DatumPolaska,
                    VrijemePolaska = v.VrijemePolaska,
                    PunaCijena = v.PunaCijena,
                    SlobodnaMjesta = v.SlobodnaMjesta,
                    GradPolaska = v.GradPolaska.Naziv,
                    GradDestinacija = v.GradDestinacija.Naziv,
                    KorisnikID = v.VozacID,

                    usputni = _db.UsputniGradovi.Where(u => u.VoznjaID == v.VoznjaID).Select(u => new SveVoznjeVM.Usputni
                    {
                        UsputniGradId = u.UsputniGradoviID,
                        Cijena = u.CijenaUsputni,
                        Naziv = u.Grad.Naziv
                    }).ToList(),

                    VoznjaID = v.VoznjaID,
                    KorisnickoIme = v.Vozac.Korisnik.Ime + " " + v.Vozac.Korisnik.Prezime
                }).ToList();

            return View(model);
        }

        public IActionResult CijenaVoznje(int voznjaID)
        {
            CijenaVoznjeVM model = new CijenaVoznjeVM();

            model = _db.Voznje.Where(v => v.VoznjaID == voznjaID).Select(v => new CijenaVoznjeVM
            {
                GradDestinacija = v.GradDestinacija.Naziv,
                GradPolazak = v.GradPolaska.Naziv
            }).FirstOrDefault();

            model.rows = new List<CijenaVoznjeVM.Row>();
            model.rows = _db.UsputniGradovi.Where(u => u.VoznjaID == voznjaID).Select(u => new CijenaVoznjeVM.Row
            {
                UsputniGradID = u.UsputniGradoviID,
                UsputniNaziv = u.Grad.Naziv,
                UsputniCijena = u.CijenaUsputni
            }).ToList();

            model.VoznjaID = voznjaID;

            return View(model);
        }

        [HttpPost]
        public IActionResult CijenaVoznje(CijenaVoznjeVM mod)
        {
            for (int i = 0; i < mod.rows.Count; i++)
            {
                UsputniGradovi usputni = _db.UsputniGradovi.Find(mod.rows[i].UsputniGradID);

                usputni.CijenaUsputni = mod.rows[i].UsputniCijena;
                _db.UsputniGradovi.Update(usputni);
            }

            _db.SaveChanges();

            return RedirectToAction(nameof(SveVoznje));
        }

        public IActionResult Dodaj()
        {
            int vozac = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            var model = new VoznjeDodajVM
            {
                GradPolaska = _db.Gradovi.OrderBy(g => g.Naziv).Select(g => new SelectListItem
                {
                    Value = g.GradID.ToString(),
                    Text = g.Naziv
                }).ToList(),
                GradDestinacija = _db.Gradovi.OrderBy(g => g.Naziv).Select(g => new SelectListItem
                {
                    Value = g.GradID.ToString(),
                    Text = g.Naziv
                }).ToList(),
                Automobili = _db.Autmobili.Where(a => a.VozacID == vozac && !a.IsAktivan).Select(a => new SelectListItem
                {
                    Value = a.AutomobilID.ToString(),
                    Text = a.Naziv + " " + a.Model
                }).ToList(),
                UsputniGradovi = _db.Gradovi.OrderBy(g => g.Naziv).Select(g => new SelectListItem
                {
                    Value = g.GradID.ToString(),
                    Text = g.Naziv
                }).ToList()
            };

            return View(model);
        }
        [HttpPost]
        public IActionResult Dodaj(VoznjeDodajVM mod)
        {
            Voznja voznja = new Voznja
            {
                GradPolaskaID = mod.GradPolaskaID,
                GradDestinacijaID = mod.GradDestinacijaID,
                AutomobilID = mod.AutomobilID,
                PunaCijena = mod.PunaCijena,
                DatumPolaska = mod.DatumPolaska,
                SlobodnaMjesta = mod.SlobodnaMjesta,
                VrijemePolaska = mod.VrijemePolaska,
                DatumObjave = DateTime.Now,
                VozacID = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)),
                VoznjaID = mod.VoznjaID,
                IsAktivna = true
            };

            _db.Add(voznja);
            _db.SaveChanges();

            if (mod.SelektiraniGradovi != null)
            {
                foreach (var selektirani in mod.SelektiraniGradovi)
                {
                    UsputniGradovi usputni = new UsputniGradovi

CarpoolApp/CarpoolApp/Areas/Driver/Views/Voznje/CijenaVoznje.cshtml
@model CarpoolApp.Areas.Driver.ViewModels.Voznje.CijenaVoznjeVM
@{
    ViewData["Title"] = "CijenaVoznje";
}

<!-- Custom scripts for this template -->
<script src="~/bootstrapTheme/js/freelancer.min.js" asp-append-version="true"></script>

<!-- Contact Section -->
<section class="page-section portfolio" id="contact">
    <div class="container">

        <!-- Contact Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">@Model.GradPolazak  <i class="fas fa-car-side"></i> @Model.GradDestinacija</h2>

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-money-bill"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <!-- Contact Section Form -->
        <div class="row">
            <div class="col-lg-8 mx-auto">

                <form enctype="multipart/form-data" action="CijenaVoznje" method="post">

                    <input asp-for="VoznjaID" hidden="hidden">

                    @for (int i = 0; i < Model.rows.Count; i++)
                    {
                        <h6>Unesite cijenu za usputni grad @Model.rows[i].UsputniNaziv.ToUpper()</h6>
                        <input asp-for="@Model.rows[i].UsputniGradID" hidden="hidden">
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                <input asp-for="@Model.rows[i].UsputniCijena" class="form-control" id="name" type="text" required="required" placeholder=" @Model.GradPolazak - @Model.rows[i].UsputniNaziv" data-validation-required-message="Molimo Vas unesite cijenu za usputni grad."><span>BAM</span>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                    }

                    @*@foreach (var item in Model.rows)
                    {
                        <h6>Unesite cijenu za usputni grad @item.UsputniNaziv.ToUpper()</h6>
                        <input asp-for="@item.UsputniGradID" hidden="hidden">
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                <input asp-for="@item.UsputniCijena" class="form-control" id="name" type="text" required="required" placeholder=" @Model.GradPolazak - @item.UsputniNaziv" data-validation-required-message="Molimo Vas unesite cijenu za usputni grad.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                    }*@

                    <br>
                    <div id="success"></div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-xl">Spasi</button>
                        <a class="btn btn-primary btn-xl" asp-area="Driver" asp-controller="Voznje" asp-action="Uredi" asp-route-voznjaID="@Model.VoznjaID">Uredi vožnju</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

CarpoolApp/CarpoolApp/Areas/Driver/Views/Voznje/MojeVoznje.cshtml
@model CarpoolApp.Areas.Driver.ViewModels.Voznje.SveVoznjeVM

@{
    ViewData["Title"] = "Moje vožnje";
}


<link href="~/bootstrapTheme/css/freelancer.css" rel="stylesheet" asp-append-version="true">

<!-- Custom styles for this template -->
<link href="~/css/Obavijesti.css" rel="stylesheet" asp-append-version="true">
<link href="~/css/voznje.css" rel="stylesheet" asp-append-version="true">

<section class="page-section portfolio" id="portfolio">
    <div class="container">

        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Moje vožnje</h2>

        <!-- Icon Divider -->
        <div style="margin:0px !important;" class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-car"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>

        <div style="text-align:center;">
            <a class="btn btn-primary" id="btnDodajVozilo" asp-area="Driver" asp-controller="Voznje" asp-action="Dodaj"><i class="fas fa-plus fa-2x"></i></a>
            <a class="btn btn-info" id="btnDodajVozilo" asp-area="Driver" asp-controller="Voznje" asp-action="ZavrseneVoznje" asp-route-vozacID="@Model.CurrentUser"><i class="fas fa-history fa-2x"></i></a>
            <br />
            <br />
        </div>

        <!-- Portfolio Grid Items -->
        <div class="row">
            @for (var i = 0; i < Model.voznje.Count(); i++)
            {
                string slikaPath = "~/imgs/" + (Model.voznje[i].SlikaPath ?? "carnotfound.jpg");
                <!-- Main Content -->
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-10 mx-auto">
                            <div class="post-preview">
                                <a class="openModalDiv" data-toggle="modal" data-target="#portfolioModal_@i">
                                    <h2 class="post-title">
                                        @Model.voznje[i].GradPolaska <i class="fa fa-arrow-right"></i> @Model.voznje[i].GradDestinacija
                                    </h2>
                                    <h5>@Model.voznje[i].PunaCijena BAM</h5>
                                </a>
                                <h5 style="float:right; padding-right:8px; padding-left:8px;"><i class="far fa-clock" style="padding-right:5px"></i>@Model.voznje[i].VrijemePolaska.ToShortTimeString()</h5>
                                <h5 style="float:right; padding-right:8px; padding-left:8px;"><i class="far fa-calendar" style="padding-right:5px"></i>@Model.voznje[i].DatumPolaska.ToShortDateString()</h5>
                                <p style="color:black;" class="post-meta">
                                    Objavio/la @Model.voznje[i].KorisnickoIme
                                </p>
                            </div>
                            <hr>
                        </div>
                    </div>
                </div>


                <!-- Portfolio Modals -->
                <div class="portfolio-modal modal fade" id="portfolioModal_@i" tabindex="-1" role="dialog" aria-labelledby="portfolioModalLabel_@i" aria-hidden="true">
                    <div class="modal-dialog modal-xl" role="document">
                        <div class="modal-content">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">
                                    <i class="fas fa-times"></i>
                                </span>
                            </button>
                            <div class="modal-body text-center">
                                <div class="container">
                                    <div class="row justify-content-center">
                                        <div class="col-lg-8">
                                            <!-- Portfolio Modal - Title -->
                                            <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">  @Model.voznje[i].GradPolaska <i class="fa fa-arrow-right"></i> @Model.voznje[i].GradDestinacija</h2>
                                            <!-- Icon Divider -->
                                            <div class="divider-custom">
                                                <div class="divider-custom-line"></div>
                                                <div class="divider-custom-icon">
                                                    <h4 style="float:right;"><i class="far fa-clock" style="padding-right:5px"></i>@Model.voznje[i].VrijemePolaska.ToShortTimeString()</h4>
                                                </div>
                                                <div class="divider-custom-line"></div>
                                            </div>



                                            @*<h4 class="post-subtitle">*@
                                            <table class="table table-borderless">
                                                @if (Model.voznje[i].usputni.Count() > 0)
                                                {
                                                    <thead>
                                                        <tr>
                                                            <th scope="col"><i class="fa fa-home"></i></th>
                                                            <th scope="col">Usputni grad</th>
                                                            <th scope="col">Cijena</th>
                                                            @if (Model.CurrentUser != Model.voznje[i].KorisnikID)
                                                            {
                                                                <th scope="col"><i class="fa fa-ticket-alt" aria-hidden="true"></i></th>
                                                            }
                                                        </tr>
                                                    </thead>

                                                    for (var j = 0; j < @Model.voznje[i].usputni.Count(); j++)
                                                    {

                                                        <tbody>
                                                            <tr>
                                                                <td>@Model.voznje[i].GradPolaska</td>
                                                                <td>@Model.voznje[i].usputni[j].Naziv</td>
                                                                <td>@Model.voznje[i].usputni[j].Cijena</td>

                                                                @if (Model.CurrentUser != Model.voznje[i].KorisnikID)
                                                                {
                                                                    <td><a asp-action="Rezervisi" asp-controller="Voznje" asp-route-usputniGradId="@Model.voznje[i].usputni[j].UsputniGradId" class="btn btn-info btn-sm" style="color:white; cursor:pointer;">Rezerviši</a></td>
                                                                }
                                                            </tr>
                                                        </tbody>

                                                    }
                                                }


                                                <tr class="border-bottom border-top">
                                                    <th>@Model.voznje[i].GradPolaska</th>
                                                    <th>@Model.voznje[i].GradDestinacija</th>
                                                    <th>@Model.voznje[i].PunaCijena</th>

                                                    @if (Model.CurrentUser != Model.voznje[i].KorisnikID)
                                                    {
                                                        <th><a asp-action="PunaRezervacija" asp-controller="Rezervacije" asp-route-voznjaID="@Model.voznje[i].VoznjaID" class="btn btn-danger btn-sm" style="color:white; cursor:pointer;">Rezerviši</a></th>
                                                    }
                                                </tr>

                                            </table>
                                            <h4>Slobodna mjesta:  @Model.voznje[i].SlobodnaMjesta</h4>


                                            <!-- Portfolio Modal - Image -->
                                            <img class="img-fluid rounded mb-5" src="@slikaPath" asp-append-version="true" />

                                            @if (Model.CurrentUser == Model.voznje[i].KorisnikID)
                                            {
                                                <a class="btn btn-secondary" asp-action="Uredi" asp-controller="Voznje" asp-route-voznjaID="@Model.voznje[i].VoznjaID">
                                                    <i class="fas fa-edit fa-fw"></i>
                                                    Uredi
                                                </a>
                                                <a class="btn btn-danger" asp-action="Obrisi" asp-controller="Voznje" asp-route-voznjaID="@Model.voznje[i].VoznjaID">
                                                    <i class="fas fa-trash fa-fw"></i>
                                                    Ukloni
                                                </a>
                                            }
                                            <button class="btn btn-primary" href="#" data-dismiss="modal">
                                                <i class="fas fa-times fa-fw"></i>
                                                Zatvori
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>